#!/bin/bash
if test -z "$1" || test ! -e "$1"; then
    echo Usage: $0 foo.c
    exit 1
fi

# basic setup
self="`readlink -f "$0"`"
topdir="`dirname "$self"`/.."
GCC="$topdir/gcc-install/bin/gcc"

# initial checks
set -x
test -x "$GCC" || exit 1

# compile
out=`mktemp`
"$GCC" "$1" -o $out -g -O0 -Wall -Wextra || exit $?

# run
valgrind $out
rv=$?

# cleanup and exit
rm -fv $out
exit $rv
