#!/bin/bash
if test -z "$1" || test ! -e "$1"; then
    echo Usage: $0 foo.c
    exit 1
fi

self="`readlink -f "$0"`"
topdir="`dirname "$self"`/.."

# basic setup
SL_DIR="$topdir/sl"
SL_BUILD="$topdir/sl_build"
SL_PLUG="$SL_BUILD/libsl.so"
CC1="../gcc-install/libexec/gcc/`ls ../gcc-install/lib/gcc/`/4.[56]*/cc1"


# attempt to make
test -x "$SL_PLUG" \
    || make -s $MAKEOPTS -C "$topdir/sl" \
    || exit 1

# prepare the command line
RUN="$CC1 \"$1\" \
    -I../cl -I../cl/gcc -I../include -I../include/gcc \
    -DPREDATOR \
    -dumpbase test.c -quiet -o /dev/null \
    -m32 -O0 -Wall -Wextra \
    -fplugin="$SL_PLUG" \
    $SL_OPTS &"

RUN="`printf "$RUN" | tr --squeeze-repeats ' '`"
printf "%s\n\n" "$RUN"
eval "$RUN"

PID_CC1=$!
trap "kill -9 $PID_CC1 2>/dev/null" EXIT

sleep 1 || exit $?
for i in `seq 150`; do
    sleep .1 || exit $?
    test -e /proc/$PID_CC1 || exit 0
done

printf "\n@ %s\n" "`date`"
while kill -SIGUSR1 $PID_CC1 2>/dev/null; do
    sleep 16 || exit $?
    printf "\n@ %s\n" "`date`"
done
