#!/bin/bash
if test -z "$1" || test ! -e "$1"; then
    echo Usage: $0 foo.c
    exit 1
fi

self="`readlink -f "$0"`"
topdir="`dirname "$self"`/.."

# basic setup
CL_DIR="$topdir/cl"
SL_DIR="$topdir/sl"
SL_BUILD="$topdir/sl_build"
SL_PLUG="$SL_BUILD/libsl.so"
CC1="../gcc-install/libexec/gcc/`ls ../gcc-install/lib/gcc/`/4.[5-7]*/cc1"

# attempt to make
make -C "$CL_DIR" -s -j5 'CMAKE=cmake -D USE_INT3_AS_BRK=ON -D CL_DEBUG=ON' \
    || exit 1
make -C "$SL_DIR" -s -j5 'CMAKE=cmake -D USE_INT3_AS_BRK=ON -D SL_DEBUG=ON' \
    || exit 1
test -x "$SL_PLUG" \
    || exit 1

# use gdb by default
test -z "$GDB" && GDB=gdb

# use verbose level 1 by default
test -z "$SL_VERBOSE" && SL_VERBOSE=1

# use pp code listener by default
test -z "$SL_OPTS" && SL_OPTS="-fplugin-arg-libsl-dump-pp"

# prepare the command line
RUN="$GDB --quiet --args $CC1 \"$1\" \
    -I../cl -I../cl/gcc -I../include -I../include/gcc \
    -DPREDATOR \
    -dumpbase test.c -quiet -o /dev/null \
    -m32 -O0 -Wall -Wextra \
    -fplugin=$SL_PLUG \
    -fplugin-arg-libsl-verbose=$SL_VERBOSE \
    $SL_OPTS"

RUN="`printf "$RUN" | tr --squeeze-repeats ' '`"
printf "\n\n%s\n\n" "$RUN"
eval "$RUN"
