#!/bin/bash
self="`readlink -f "$0"`"
topdir="`dirname "$self"`/.."

# use chromium as default SVG_VIEWER
test -z "$SVG_VIEWER" && SVG_VIEWER=chromium

# visualize graphs
printf "graph visualization in progress ... "
make $MAKEOPTS -s -f "$topdir/tests/predator-regre/Makefile.in" \
    TIMEOUT="timeout 2" || exit $?
printf "done\n"

if test -r fp-main.svg; then
    "$SVG_VIEWER" fp-main.svg
else
    "$SVG_VIEWER" *.svg
fi 2>/dev/null &
