#!/bin/bash

# Simple wrapping script for running Code-Listener with a C compiler.
# Author: Dee'Kej (deekej@linuxmail.org)

if [[ $# -ne 1 ]]; then
  echo "Usage: $0 source-file" >&2
  exit 1
fi

#export GCC_PROG_NAME="cc1"     # C compiler is used by default.
#export GCC_PARAMS="-fno-rtti -fno-exceptions"  # Irrelevant flags for C lang.

./vkdebug.sh "$1"

exit $?
