#!/bin/bash

# Simple wrapping script for running Code-Listener with a C++ compiler.
# Author: Dee'Kej (deekej@linuxmail.org)

if [[ $# -ne 1 ]]; then
  echo "Usage: $0 source-file" >&2
  exit 1
fi

export GCC_PROG_NAME="cc1plus"      # Internal naming of g++ inside the gcc.
export GCC_PARAMS="-fno-rtti -fno-exceptions"

./vkdebug.sh "$1"

exit $?
