#include <stdlib.h>

extern int __VERIFIER_nondet_int(void);

int main() {
	int n = 1;
	while(__VERIFIER_nondet_int() && n < 5) {
		n++;
	}

	int array[n];
	int* p = &array[1];
	int ret = p[n-2]; // without errors

	return ret;
}

/**
 * @file test-0246.c
 *
 * @brief a regression test for ptr wrap-around generated by gcc -m32
 *
 * @attention
 * This description is automatically imported from tests/predator-regre/README.
 * Any changes made to this comment will be thrown away on the next import.
 */
