#!/bin/sh

# use etags by default; $ETAGS if specified
test -z $ETAGS && ETAGS=etags

# check $ETAGS availability
if $ETAGS --help >/dev/null 2>&1; then
    # found
    true
else
    echo "$0: error: '$ETAGS' not found"
    exit 1
fi

# use the current directory if called without any parameter
dir=$1
test -z $dir && dir=.

# solution taken from
# http://osdir.com/ml/lang.caml.inria/2001-07/msg00113.html
find $dir -name "*.ml" | xargs $ETAGS \
    "--regex=/let[ \t]+\([^ \t]+\)/\1/" \
    "--regex=/let[ \t]+rec[ \t]+\([^ \t]+\)/\1/" \
    "--regex=/and[ \t]+\([^ \t]+\)/\1/" \
    "--regex=/type[ \t]+\([^ \t]+\)/\1/" \
    "--regex=/exception[ \t]+\([^ \t]+\)/\1/" \
    "--regex=/val[ \t]+\([^ \t]+\)/\1/" \
    "--regex=/module[ \t]+\([^ \t]+\)/\1/"
