#!/bin/bash
if test -z "$1" || test ! -e "$1"; then
    echo "Usage: $0 foo.c <box directory>"
    exit 1
fi

# basic setup
set -x
FA_BUILD=../fa_build
FA_PLUG="$FA_BUILD/libfa.so"
#CC1="../gcc-install/libexec/gcc/`ls ../gcc-install/lib/gcc/`/4.[56]*/cc1"
CC1=" /usr/lib/gcc/x86_64-linux-gnu/4.6/cc1"

# initial checks
eval test -x "$CC1"             || exit 1
test -d "$FA_BUILD"             || exit 1
test -f "$FA_BUILD/Makefile"    || exit 1

# attempt to make
make -C "$FA_BUILD"             || exit 1
test -x "$FA_PLUG"              || exit 1

# use gdb by default
test -z "$GDB" && GDB=gdb

# use verbose level 1 by default
test -z "$FA_VERBOSE" && FA_VERBOSE=1

# use pp code listener by default
test -z "$FA_OPTS" && FA_OPTS="-fplugin-arg-libfa-dump-pp -fplugin-arg-libfa-dump-types"

BOXDB=""
if [ "$2" != "" ]; then
    BOXDB="-fplugin-arg-libfa-args=db-root:$2"
fi

# run the debugger
eval LD_PRELOAD=/lib/x86_64-linux-gnu/libpthread.so.0 "$GDB" --quiet --args "$CC1" "$1" \
    -DFORESTER \
    -dumpbase test.c -quiet -o /dev/null \
    -m32 -O0 -Wall -Wextra \
    -fplugin="$FA_PLUG" \
    -fplugin-arg-libfa-verbose="$FA_VERBOSE" \
    $BOXDB \
    $FA_OPTS
